def find_the_capital():
    print("\nEnter the country, and I will give you its capital.")
    while True:
        try:
            a = input("If you want to see countries when I know, enter 'y'; if you don't want, enter 'n': ")
            if a.lower() == 'y' or a.lower() == 'n':
                break
        except ValueError:
            print("It isn't a valid input.")
    capitals = {
        "Afghanistan": "Kabul",
        "Albania": "Tirana",
        "Algeria": "Algiers",
        "Andorra": "Andorra la Vella",
        "Angola": "Luanda",
        "Antigua and Barbuda": "St. John's",
        "Argentina": "Buenos Aires",
        "Armenia": "Yerevan",
        "Australia": "Canberra",
        "Austria": "Vienna",
        "Azerbaijan": "Baku",
        "Bahamas": "Nassau",
        "Bahrain": "Manama",
        "Bangladesh": "Dhaka",
        "Barbados": "Bridgetown",
        "Belarus": "Minsk",
        "Belgium": "Brussels",
        "Belize": "Belmopan",
        "Benin": "Porto-Novo",
        "Bhutan": "Thimphu",
        "Bolivia": "Sucre",
        "Bosnia and Herzegovina": "Sarajevo",
        "Botswana": "Gaborone",
        "Brazil": "Brasília",
        "Brunei": "Bandar Seri Begawan",
        "Bulgaria": "Sofia",
        "Burkina Faso": "Ouagadougou",
        "Burundi": "Bujumbura",
        "Cambodia": "Phnom Penh",
        "Cameroon": "Yaoundé",
        "Canada": "Ottawa",
        "Cape Verde": "Praia",
        "Central African Republic": "Bangui",
        "Chad": "N'Djamena",
        "Chile": "Santiago",
        "China": "Beijing",
        "Colombia": "Bogotá",
        "Comoros": "Moroni",
        "Congo (Congo-Brazzaville)": "Brazzaville",
        "Costa Rica": "San José",
        "Croatia": "Zagreb",
        "Cuba": "Havana",
        "Cyprus": "Nicosia",
        "Czechia (Czech Republic)": "Prague",
        "Denmark": "Copenhagen",
        "Djibouti": "Djibouti",
        "Dominica": "Roseau",
        "Dominican Republic": "Santo Domingo",
        "East Timor (Timor-Leste)": "Dili",
        "Ecuador": "Quito",
        "Egypt": "Cairo",
        "El Salvador": "San Salvador",
        "Equatorial Guinea": "Malabo",
        "Eritrea": "Asmara",
        "Estonia": "Tallinn",
        "Eswatini (fmr. Swaziland)": "Mbabane",
        "Ethiopia": "Addis Ababa",
        "Fiji": "Suva",
        "Finland": "Helsinki",
        "France": "Paris",
        "Gabon": "Libreville",
        "Gambia": "Banjul",
        "Georgia": "Tbilisi",
        "Germany": "Berlin",
        "Ghana": "Accra",
        "Greece": "Athens",
        "Grenada": "St. George's",
        "Guatemala": "Guatemala City",
        "Guinea": "Conakry",
        "Guinea-Bissau": "Bissau",
        "Guyana": "Georgetown",
        "Haiti": "Port-au-Prince",
        "Honduras": "Tegucigalpa",
        "Hungary": "Budapest",
        "Iceland": "Reykjavik",
        "India": "New Delhi",
        "Indonesia": "Jakarta",
        "Iran": "Tehran",
        "Iraq": "Baghdad",
        "Ireland": "Dublin",
        "Israel": "Jerusalem",
        "Italy": "Rome",
        "Ivory Coast (Côte d'Ivoire)": "Yamoussoukro",
        "Jamaica": "Kingston",
        "Japan": "Tokyo",
        "Jordan": "Amman",
        "Kazakhstan": "Nur-Sultan",
        "Kenya": "Nairobi",
        "Kiribati": "South Tarawa",
        "Korea, North": "Pyongyang",
        "Korea, South": "Seoul",
        "Kosovo": "Pristina",
        "Kuwait": "Kuwait City",
        "Kyrgyzstan": "Bishkek",
        "Laos": "Vientiane",
        "Latvia": "Riga",
        "Lebanon": "Beirut",
        "Lesotho": "Maseru",
        "Liberia": "Monrovia",
        "Libya": "Tripoli",
        "Liechtenstein": "Vaduz",
        "Lithuania": "Vilnius",
        "Luxembourg": "Luxembourg City",
        "Madagascar": "Antananarivo",
        "Malawi": "Lilongwe",
        "Malaysia": "Kuala Lumpur",
        "Maldives": "Male",
        "Mali": "Bamako",
        "Malta": "Valletta",
        "Marshall Islands": "Majuro",
        "Mauritania": "Nouakchott",
        "Mauritius": "Port Louis",
        "Mexico": "Mexico City",
        "Micronesia": "Palikir",
        "Moldova": "Chisinau",
        "Monaco": "Monaco",
        "Mongolia": "Ulaanbaatar",
        "Montenegro": "Podgorica",
        "Morocco": "Rabat",
        "Mozambique": "Maputo",
        "Myanmar (formerly Burma)": "Naypyidaw",
        "Namibia": "Windhoek",
        "Nauru": "Yaren District",
        "Nepal": "Kathmandu",
        "Netherlands": "Amsterdam",
        "New Zealand": "Wellington",
        "Nicaragua": "Managua",
        "Niger": "Niamey",
        "Nigeria": "Abuja",
        "North Macedonia": "Skopje",
        "Norway": "Oslo",
        "Oman": "Muscat",
        "Pakistan": "Islamabad",
        "Palau": "Ngerulmud",
        "Panama": "Panama City",
        "Papua New Guinea": "Port Moresby",
        "Paraguay": "Asunción",
        "Peru": "Lima",
        "Philippines": "Manila",
        "Poland": "Warsaw",
        "Portugal": "Lisbon",
        "Qatar": "Doha",
        "Romania": "Bucharest",
        "Russia": "Moscow",
        "Rwanda": "Kigali",
        "Saint Kitts and Nevis": "Basseterre",
        "Saint Lucia": "Castries",
        "Saint Vincent and the Grenadines": "Kingstown",
        "Samoa": "Apia",
        "San Marino": "San Marino",
        "Sao Tome and Principe": "Sao Tome",
        "Saudi Arabia": "Riyadh",
        "Senegal": "Dakar",
        "Serbia": "Belgrade",
        "Seychelles": "Victoria",
        "Sierra Leone": "Freetown",
        "Singapore": "Singapore",
        "Slovakia": "Bratislava",
        "Slovenia": "Ljubljana",
        "Solomon Islands": "Honiara",
        "Somalia": "Mogadishu",
        "South Africa": "Pretoria",
        "South Sudan": "Juba",
        "Spain": "Madrid",
        "Sri Lanka": "Colombo",
        "Sudan": "Khartoum",
        "Suriname": "Paramaribo",
        "Sweden": "Stockholm",
        "Switzerland": "Bern",
        "Syria": "Damascus",
        "Tajikistan": "Dushanbe",
        "Tanzania": "Dodoma",
        "Thailand": "Bangkok",
        "Togo": "Lome",
        "Tonga": "Nuku'alofa",
        "Trinidad and Tobago": "Port of Spain",
        "Tunisia": "Tunis",
        "Turkey": "Ankara",
        "Turkmenistan": "Ashgabat",
        "Tuvalu": "Funafuti",
        "Uganda": "Kampala",
        "Ukraine": "Kyiv",
        "United Arab Emirates": "Abu Dhabi",
        "United Kingdom": "London",
        "United States": "Washington, D.C.",
        "Uruguay": "Montevideo",
        "Uzbekistan": "Tashkent",
        "Vanuatu": "Port Vila",
        "Vatican City": "Vatican City",
        "Venezuela": "Caracas",
        "Vietnam": "Hanoi",
        "Yemen": "Sana'a",
        "Zambia": "Lusaka",
        "Zimbabwe": "Harare",
    }
    if a.lower() == 'y':
        for i, (country, capital) in enumerate(capitals.items(), start=1):
            print(f"{i}. {country}", end="")
            if i == len(capitals):
                print(".")
            else:
                print(";")
    find = input("\nCountry - ")
    for i, (country, capital) in enumerate(capitals.items(), start=1):
        if find.lower() == country.lower():
            return print(f"\n{capital} is the capital of {country}.\nCountry by number \"{i}\".")
    return print("\nI'm sorry so sorry.\nI don't know this country.")
